import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://images-na.ssl-images-amazon.com/images/I/71HqMrVQWKL._UL500_.jpg",
    title: "Mora Ceramic",
    star: <AiFillStar className="rating-star" />,
    reviews: "(58 reviews)",
    prevPrice: "R170,00",
    newPrice: "150",
    company: "Artful Home",
    color: "white",
    category: "Ceramics",
  },
  {
    img: "https://ponieskrantz.co.za/wp/wp-content/uploads/2022/04/PK_RimDinner_RimSide_Plate_Turq1-1.jpg",
    title: "Side Plate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "R140,00",
    newPrice: "100",
    company: "Artful Home",
    color: "blue",
    category: "Ceramics",
  },

  {
    img: "https://www.foodandwine.com/thmb/uuSw-ImRer6sgeEzyzUWMA0_SPI=/fit-in/1300x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/faw-costa-nova-livia-ceramic-dinnerware-set-katie-brown-15-cd10e7d6642e4964924704f7cf59d794.jpeg",
    title: "Dinner Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(113 reviews)",
    prevPrice: "R350,00",
    newPrice: "200",
    company: "Artful Home",
    color: "pink",
    category: "Ceramics",
  },
  {
    img: "https://cdn.shopify.com/s/files/1/0024/4137/9915/files/beige-main-plates.jpg?v=1733780701&width=767&height=767&crop=center",
    title: "Main Plates",
    star: <AiFillStar className="rating-star" />,
    reviews: "(98 reviews)",
    prevPrice: "R240,00",
    newPrice: "200",
    company: "CraftCorner",
    color: "grey",
    category: "Ceramics",
  },
  {
    img: "https://thefoschini.vtexassets.com/arquivos/ids/174467977-1200-1600?v=638727023220370000&width=1200&height=1600&aspect=true",
    title: "Maxwell Coffee Mug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(126 reviews)",
    prevPrice: "R65,00",
    newPrice: "50",
    company: "Artful Home",
    color: "black",
    category: "Ceramics",
  },
  {
    img: "https://thefoschini.vtexassets.com/arquivos/ids/179156324-1200-1600?v=638760056143230000&width=1200&height=1600&aspect=true",
    title: "Tokyo Coffee Mug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(73 reviews)",
    prevPrice: "R40,00",
    newPrice: "50",
    company: "Artful Home",
    color: "blue",
    category: "Ceramics",
  },

  {
    img: "https://thefoschini.vtexassets.com/arquivos/ids/180110604-1200-1600?v=638766877613030000&width=1200&height=1600&aspect=true",
    title: "Ella Mug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(33 reviews)",
    prevPrice: "R67,00",
    newPrice: "50",
    company: "CraftCorner",
    color: "white",
    category: "Ceramics",
  },
  {
    img: "https://www.africanfabric.co.uk/custom/library/F000030/afs-51374-jan-roberts-kuba-cushions-KGX91C-l.jpg",
      title: "Kuba Cushions",
      star: <AiFillStar className="rating-star" />,
      reviews: "(43 reviews)",
      prevPrice: "R170,00",
      newPrice:"150",
      company: "EcoCrafts",
      color: "black",
      category: "Textile"
  },

  {
    img: "https://www.argillapottery.co.za/wp-content/uploads/2024/12/coffee-mugs-green.png",
    title: "Sandtone Mug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "R110,00",
    newPrice: "100",
    company: "CraftCorner",
    color: "green",
    category: "Ceramics",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqXQk8muLUOarezPOAW187G3VbLS9AAeGzpw&s",
    title: "Beads Earrings",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "R75,00",
    newPrice:"50",
    company: "CraftCorner",
    color: "green",
    category: "Jewelry",
  },
  {
  img: "https://www.southafricanbracelets.com/cdn/shop/products/TRADITIONAL_COLORED_BEADED_NECKLACE-BLUE_grande_bd0c71f8-822b-4181-9641-c8e6c13d973b.jpg?v=1526674322",
    title: "Traditional Necklace",
    star: <AiFillStar className="rating-star" />,
    reviews: "(61 reviews)",
    prevPrice: "R115,00",
    newPrice:"100",
    company: "CraftCorner",
    color: "blue",
    category: "Jewelry"
   },

   {
    img: "https://hemingwaygallery.nyc/cdn/shop/files/Red_Yellow_Zulu_Beaded_Necklace_1.jpg?v=1739374602",
      title: "Traditional Necklace",
      star: <AiFillStar className="rating-star" />,
      reviews: "(61 reviews)",
      prevPrice: "R330,00",
      newPrice:"250",
      company: "CraftCorner",
      color: "red",
      category: "Jewelry"
  },
  {
    img: "https://thumbs.dreamstime.com/b/south-african-jewelry-necklace-earrings-handmade-africa-34919362.jpg",
      title: "Beads Necklace",
      star: <AiFillStar className="rating-star" />,
      reviews: "(56 reviews)",
      prevPrice: "R320,00",
      newPrice:"250",
      company: "EcoCrafts",
      color: "black",
      category: "Jewelry"
  },

  {
    img: "https://i0.wp.com/hojjati.com.au/wp-content/uploads/2024/03/Afghan-Handmade-Rug-Wool-Red-300X200-2.jpg?fit=1280%2C1278&ssl=1",
      title: "Handmade Rug",
      star: <AiFillStar className="rating-star" />,
      reviews: "(43 reviews)",
      prevPrice: "R150,00",
      newPrice:"100",
      company: "EcoCrafts",
      color: "red",
      category: "Textile"
  },
 
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs88AqgHfEtJ4i2YMfzKyZAy1CEmRZ5uCjIw&s",
      title: "Shweshwe Fabrics",
      star: <AiFillStar className="rating-star" />,
      reviews: "(43 reviews)",
      prevPrice: "R360,00",
      newPrice:"250",
      company: "CraftCorner",
      color: "blue",
      category: "Textile"
  },
  {
    img: "https://www.southafricanbracelets.com/cdn/shop/products/TRADITIONAL_COLORED_BEADED_NECKLACE-GREEN_grande_a7f048cf-2b99-4d52-9b87-5fcf2b2bb42a.jpg?v=1526676547",
      title: "Traditional Necklace",
      star: <AiFillStar className="rating-star" />,
      reviews: "(45 reviews)",
      prevPrice: "R339,00",
      newPrice:"250",
      company: "EcoCrafts",
      color: "green",
      category: "Jewelry"
  },
]

export default data;